### ISSUE TITLE
[BUG] Default execution should not check mutually exclusive rules

### ISSUE THREAD

**Issue by aaronsteers** [prospector-dev/prospector#370]
**Describe the bug**

Currently the default execution of prospector throws errors for mutually exclusive rules: PEP257-D212 and D213.

 - https://stackoverflow.com/questions/45990301/pep257-d212-and-d213-conflicts/60687485#60687485

**To Reproduce**

Run prospector through VS Code with args specified.

Multi-line doc strings will trigger D212 and if you change the docstring to match the convention, it will then trigger D213. See the stackoverflow link above.

**Expected behavior**

The expected behavior is that there is always a solution to resolving style errors and warnings. There should be no cases where mutually exclusive rules contradict each other.

**Screenshots**

n/a

**Environment (please complete the following information):**
 - OS: Windows
 - Tool : pylint
 - Prospector version : 1.2.0
 - Python version : 3.8.1

**Additional context**

Curiously, a workaround is to use the command-line `--profile=default` to use the built-in profile stored [here](https://github.com/PyCQA/prospector/tree/master/prospector/profiles/profiles). If needed, this profile should be taken automatically when no other profile is specified, in order to avoid circulular or contradictory rulesets conflicting with each other in the `default` CLI experience.

**Comment by casperdcl** [comment]
This is still an issue on https://codacy.com which uses `prospector==1.18.0` and always triggers either D212 or D213 on any python project by default.
