### ISSUE TITLE
[BUG] django is needed to run pylint after fresh prospector installation

### ISSUE THREAD

**Issue by mdabrowski1990** [prospector-dev/prospector#443]
**Describe the bug**
During `prospector` installation, `pylint-django` is also installed. The problem is that [pylint-django shall only be used with django](https://github.com/PyCQA/pylint-django/issues/327)

**To Reproduce**
1) create fresh interpreter (without django installed)
2) install prospector:
`pip install prospector==1.5.1`
3) run prospector on any project:
`prospector`
4) pylint fails to run:
```
  Line: None
    pylint: failure / Tool pylint failed to run (exception was raised, re-run prospector with -X to see the stacktrace)
```

**Expected behavior**
After the installation, `prospector` is ready to be run.

**Environment (please complete the following information):**
- Tool: `pylint` and `pylint-django`
- Prospector version: 1.5.1
- Python version: 3.9.7 (but I expect that all python 3 versions are affected)

**Additional context**
Full traceback of error after fresh `prospector` installation:
```
(venv) C:\Repos\uds>prospector
Traceback (most recent call last):
  File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Repos\uds\venv\lib\site-packages\prospector\__main__.py", line 6, in <module>
    sys.exit(main())
  File "C:\Repos\uds\venv\lib\site-packages\prospector\run.py", line 183, in main
    prospector.execute()
  File "C:\Repos\uds\venv\lib\site-packages\prospector\run.py", line 69, in execute
    messages += tool.run(found_files)
  File "C:\Repos\uds\venv\lib\site-packages\prospector\tools\pylint\__init__.py", line 259, in run
    self._linter.check(self._args)
  File "C:\Repos\uds\venv\lib\site-packages\pylint\lint\pylinter.py", line 970, in check
    self._check_files(
  File "C:\Repos\uds\venv\lib\site-packages\pylint\lint\pylinter.py", line 1005, in _check_files
    with self._astroid_module_checker() as check_astroid_module:
  File "C:\Python39\lib\contextlib.py", line 119, in __enter__
    return next(self.gen)
  File "C:\Repos\uds\venv\lib\site-packages\pylint\lint\pylinter.py", line 1127, in _astroid_module_checker
    checker.open()
  File "C:\Repos\uds\venv\lib\site-packages\pylint_django\checkers\foreign_key_strings.py", line 83, in open
    from django.core.exceptions import (  # pylint: disable=import-outside-toplevel
ModuleNotFoundError: No module named 'django'
```
When I unistall pylint-django:
`pip uninstall pylint-django`
Suddendly, everything is ok.

I would consider removal of `pylint-django` pluggin from base project dependencies.

At the moment, I would do following workaround in my project:
```
pip install prospector==1.5.1
pip unistall pylint-django -y
```

**Comment by mdabrowski1990** [comment]
From what I see, it is enough to set `autodetect: false` in profile file.
Nevertheless, it is strange that prospector decided that I am using both django and flask even though I do no have them even isntalled...

**Comment by carlio** [comment]
The autodetect works by searching for references to Django in the requirements, or any imports - https://github.com/PyCQA/prospector/blob/master/prospector/autodetect.py#L19

**Comment by carlio** [comment]
I suspect this is pylint-django enforcing Django these days though.

**Comment by mdabrowski1990** [comment]
> I suspect this is pylint-django enforcing Django these days though.

It seems so, as this is exactly what I observed.

In my opinion, the only thing that could be done here, would be reviewing (maybe some update?) autodetection feature as it seems that it does not work as intended (as you mentioned `pylint-django` that is installed with `prospector` enforces Django usage).
Honestly, I have managed to solve the problem for myself (autdetection configuration in the profile file works just fine), therefore it is up to you whether what you want to fix this one.

**Comment by Lx** [comment]
I'm getting Prospector errors `Django is not available on the PYTHONPATH` for all of my source files in a project that doesn't use Django.  I find this remark confusing:

> The autodetect works by searching for references to Django in the requirements, or any imports - https://github.com/PyCQA/prospector/blob/master/prospector/autodetect.py#L19

because none of my source files have any Django references, and neither does my `pyproject.toml` file.

It seems that Poetry is installing `pylint-django` because it's listed as a requirement of `prospector`.  Can this potentially be moved out into an optional dependency?

**Comment by Mikaciu** [comment]
Hello, 

Another workaround would be to disable the check:
```yaml
pylint:
  disable:
    - django-not-available
```

**Comment by sbrunner** [comment]
Issue closed because there are no resent messages, if you are still impacted please, 
test with the latest version of Prospector (>= 1.12.1) 
and reopen it with a message like "still valid, tested with the version <version>".
