### ISSUE TITLE
[BUG] No module named 'setoptconf'

### ISSUE THREAD

**Issue by username-dot-com** [prospector-dev/prospector#504]
**Describe the bug**
I try to run prospector and it throws a ModuleNotFoundError saying there isn't a module named `setoptconf`. Looking at the issues, it seems that this issue should have been solved?
I've installed prospector using poetry if that matters? I've checked the lock file and the venv and both have the temporary package `setoptconf-tmp` installed. 

**To Reproduce**
1. Go to project root
2. Call `poetry run prospector <src_root>`
3. See error

**Expected behavior**
Prospector runs

**Environment (please complete the following information):**
 - OS: linux
 - Prospector version: 1.7.7
- Python version: 3.9.5

**Additional context**
I'm using `with_mypy` and `with_bandit` extras.

**Comment by soar** [comment]
I've got the same issue after upgrading

**Comment by sbrunner** [comment]
Issue closed because there are no resent messages, if you are still impacted please, 
test with the latest version of Prospector (>= 1.12.1) 
and reopen it with a message like "still valid, tested with the version <version>".
