### ISSUE TITLE
[BUG] mypy run crashes when json file in .mypy_cache directory is corrupt

### ISSUE THREAD

**Issue by SubaruArai** [prospector-dev/prospector#509]
**Describe the bug**
When a json file is corrupt or empty in the `.mypy_cache` directory, mypy will return the following message:

> path/to/file.json: error: Error reading JSON file; you likely have a bad cache.\nTry removing the .mypy_cache directory and run mypy again.\n
This behavior is from [this part of the code](https://github.com/python/mypy/blob/612074f05ba5d65e016c031dc94b13f962d9c6b4/mypy/build.py#L1109).

Then prospector tries to parse this message with [this part of code](https://github.com/PyCQA/prospector/blob/a5a642c340b9155a21d9df48b575241d3df67cb8/prospector/tools/mypy/__init__.py#L24).
The problem is, it expects one error message per input, but the output from mpy is [processed beforehand using `splitline`](https://github.com/PyCQA/prospector/blob/a5a642c340b9155a21d9df48b575241d3df67cb8/prospector/tools/mypy/__init__.py#L116)

I'm not sure about other messages that mypy returns, so am not sure how to fix this without breaking other things. (do we need `splitline`?)

**To Reproduce**
1. prepare a repository with prospector and mypy through prospector enabled
2. run prospector once, and let mypy generate `.mypy_cache`
3. in `.mypy_cache`, corrupt a json file, preferably `*.meta.json`.
  - you can delete a bracket, or delete all the text inside (make it a blank file) to corrupt the file.
4.  rum prospector with -X, or even better, use a debugger and see the error

**Expected behavior**
Prospector does not crash, and passes the message that mypy returned.

**Environment (please complete the following information):**
 - OS: Ubuntu 20.04LTS
 - Tool: mypy 0.942
 - Prospector version: 1.7.7
- Python version: 3.8.10

**Additional context**
Both master branches of prospector and mypy contained that piece of code that was causing the problem.

**Comment by sbrunner** [comment]
Issue closed because there are no resent messages, if you are still impacted please, 
test with the latest version of Prospector (>= 1.12.1) 
and reopen it with a message like "still valid, tested with the version <version>".
