### ISSUE TITLE
[BUG] mypy option 'implicit-optional' doesn't work due to typo in prospector/tools/mypy/__init__.py

### ISSUE THREAD

**Issue by rambutandev** [prospector-dev/prospector#584]
prospector/tools/mypy/__init__.py
on lines 73 and 79 there is typo and instead of 'implicit-optional' it's 'impli**ct**-optional'

this option doesn't work due to this bug

**Comment by Pierre-Sassoulas** [comment]
You can open a pull request directly for this kind of thing :)

**Comment by sbrunner** [comment]
In the mypy documentation, I see with the 'i'!
https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-implicit-optional

**Comment by sbrunner** [comment]
Reopen it if it looks to be a valid issue.
