### ISSUE TITLE
[BUG] Relative import false negatives

### ISSUE THREAD

**Issue by rpatterson** [prospector-dev/prospector#596]
**Describe the bug**

If `./src/foo/tests/__init__.py` defines a project-specific base test case class:

    class FooTestCase(unittest.TestCase):

And then an actual test module uses a relative import to use that base class:

    from .. import tests
    
    class BarTests(tests.FooTestCase):

Running `$ pylint ./src/foo` directly doesn't report any error but running `$ prospector ./src/foo` reports `pylint: relative-beyond-top-level / Attempted relative import beyond top-level package`.

**To Reproduce** Steps to reproduce the behavior:

1. `$ prospector ./src/foo`

**Expected behavior**

Prospector should report no errors the same as running PyLint directly does.

**Environment:**

- OS: Docker `python:3.11` image
- Tool: pylint
- Prospector version: v1.9.0
- Python version: v3.11.2

**Additional context**

I've also observed this with `from . import bar` relative imports so I think the issue is a general issue with relative imports and not specific to just the given example case.

**Comment by rpatterson** [comment]
May be related to [my other Prospector issue](https://github.com/PyCQA/prospector/issues/595#issue-1592491601).  It seems like Prospector may be stripping some context or not providing some context that PyLint uses to identify package hierarchy, class hierarchy, etc..

**Comment by sbrunner** [comment]
Issue closed because there are no resent messages, if you are still impacted please, 
test with the latest version of Prospector (>= 1.12.1) 
and reopen it with a message like "still valid, tested with the version <version>".

**Comment by rpatterson** [comment]
> Issue closed because there are no resent messages, if you are still impacted please, 
> test with the latest version of Prospector (>= 1.12.1) 
> and reopen it with a message like "still valid, tested with the version <version>".

See [my comment on my other issue](https://github.com/prospector-dev/prospector/issues/599#issuecomment-2408816193) for user feedback about why I'll be moving away from prospector entirely, not retesting with the most recent version.
