### ISSUE TITLE
[BUG] Vulture doesn't report `unused method` under Prospector

### ISSUE THREAD

**Issue by rpatterson** [prospector-dev/prospector#598]
**Describe the bug**

Running Vulture directly reports `unused method`:

```
$ vulture ./src/foo/
src/foo/bar.py:##: unused method 'qux' (##% confidence)
```

But running it under Prospector reports nothing:

```
$ prospector ./src/foo/
Check Information
=================
         Started: ####-##-## ##:##:##.######
        Finished: ####-##-## ##:##:##.######
      Time Taken: #.## seconds
       Formatter: grouped
        Profiles: .prospector.yaml, full_pep8, doc_warnings, strictness_veryhigh, member_warnings
      Strictness: from profile
  Libraries Used: 
       Tools Run: bandit, dodgy, mccabe, mypy, profile-validator, pycodestyle, pydocstyle, pyflakes, pylint, vulture
  Messages Found: 0
 External Config: pylint: ./pyproject.toml
```

**Environment:**

- OS: Docker `python:3.11` image
- Tool: pylint
- Prospector version: v1.9.0
- Python version: v3.11.2

**Comment by rpatterson** [comment]
I'm guessing this is because Prospector [hard codes the vulture checks to perform](https://github.com/PyCQA/prospector/blob/master/prospector/tools/vulture/__init__.py#L43-L46)?  Maybe it would be best to find someway to let Vulture define the list of checks it performs so that they're included in Prospector as Vulture changes?

**Comment by sbrunner** [comment]
Issue closed because there are no resent messages, if you are still impacted please, 
test with the latest version of Prospector (>= 1.12.1) 
and reopen it with a message like "still valid, tested with the version <version>".
