### ISSUE TITLE
[PKG SUPPORT] changes for support of `flake >=6.0.0` (and Python 3.12, implicit)

### ISSUE THREAD

**Issue by valeriupredoi** [prospector-dev/prospector#644]
Hi @carlio et al (the good Prospector folk), here's your (annoying) friendly pkg maintainer - in order for Prospector to be built with Python 3.12, there are three direct dependencies that need to change lower and upper pin bounds (well, upper bound is not 100% needed, but safe):

```
- mccabe >=0.7.0,<0.8.0
- pycodestyle >=2.11.0,<2.12.0
- pyflakes >=3.1.0,<3.2.0
```

these are unfortunately dictated by `flake8 >=6`. Are these possible at the moment? If so, I can fire up a rebuild, and (AFAIK) even with a `pylint=2.17.7` we can get us a python 3.12 supported build, so the issue of supporting pylint >=3 is not that pressing, Python 3.12-wise. Cheers muchly! :beer:

**Comment by Pierre-Sassoulas** [comment]
Hey, thank you for the investigation :) Feel free to open a merge request as most of the work is done. pylint 2.17.7 works with python 3.12 as long as you don't use 3.12 specific structure, but we do need pylint > 3 in the general case.

**Comment by valeriupredoi** [comment]
cheers muchly, mate! Will open a PR on the feedstock, and let you guys do the changes upstream :beer:

**Comment by valeriupredoi** [comment]
I have opened https://github.com/landscapeio/prospector/pull/645 for upstream deps and a DNMY PR at the feedstock https://github.com/conda-forge/prospector-feedstock/pull/44 that should wait for the upstream one - in the meantime I've realized that flake8>=6 will mean loss of support for Python 3.7 which is up to you guys to decide if can be done or not. At any rate, let me know if I can do anything else, and have a good weekend in the meantime :beer:

**Comment by sbrunner** [comment]
Looks to be fixed :-)
